"""Fail-closed transaction-engine integration tests on disposable PostgreSQL only."""
import os
import unittest
from pathlib import Path

import psycopg2
from psycopg2.extensions import parse_dsn

DSN = os.getenv("POLK_TEST_DB_URL")
ROOT = Path(__file__).resolve().parents[1]
MIGRATIONS = [
    ROOT / "supabase/migrations/20261003191244_transaction_engine_core.sql",
    ROOT / "supabase/migrations/20261003191417_transaction_hash_extension_resolution.sql",
    ROOT / "supabase/migrations/20261003191433_transaction_engine_hash_path.sql",
    ROOT / "supabase/migrations/20261003192520_contract_rendering_esign_guard.sql",
    ROOT / "supabase/migrations/20261003193650_contract_rendering_idempotent_replay.sql",
]


@unittest.skipUnless(DSN, "requires disposable localhost PostgreSQL")
class TransactionEnginePostgresTests(unittest.TestCase):
    def setUp(self):
        parsed = parse_dsn(DSN)
        if (
            parsed.get("host") not in ("localhost", "127.0.0.1")
            or parsed.get("port") != "55432"
            or parsed.get("dbname") != "postgres"
            or parsed.get("hostaddr")
        ):
            raise RuntimeError("Disposable database required")

        self.db = psycopg2.connect(DSN)
        self.addCleanup(self.db.close)

        with self.db, self.db.cursor() as c:
            c.execute(
                """
                DROP SCHEMA IF EXISTS god_mode_ops CASCADE;
                DROP SCHEMA IF EXISTS cron CASCADE;
                DROP EXTENSION IF EXISTS pgcrypto CASCADE;
                DROP SCHEMA IF EXISTS extensions CASCADE;
                DROP TABLE IF EXISTS public.outreach_events CASCADE;
                DROP TABLE IF EXISTS public.buyer_matches CASCADE;
                DROP TABLE IF EXISTS public.buyers CASCADE;
                DROP TABLE IF EXISTS public.polk_legal_v2 CASCADE;
                DROP TABLE IF EXISTS public.due_diligence_reviews CASCADE;
                DROP TABLE IF EXISTS public.deals CASCADE;
                DROP TABLE IF EXISTS public.leads CASCADE;
                DROP TABLE IF EXISTS public.properties CASCADE;
                """
            )
            c.execute(
                """
                DO $$
                BEGIN
                  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN CREATE ROLE anon; END IF;
                  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN CREATE ROLE authenticated; END IF;
                  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='service_role') THEN CREATE ROLE service_role; END IF;
                END
                $$;
                CREATE SCHEMA extensions;
                CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;
                CREATE SCHEMA cron;
                CREATE TABLE cron.job(
                  jobid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  jobname text UNIQUE NOT NULL,
                  schedule text NOT NULL,
                  command text NOT NULL,
                  active boolean NOT NULL DEFAULT true
                );
                CREATE FUNCTION cron.schedule(p_jobname text,p_schedule text,p_command text)
                RETURNS bigint
                LANGUAGE plpgsql
                AS $$
                DECLARE v_id bigint;
                BEGIN
                  INSERT INTO cron.job(jobname,schedule,command,active)
                  VALUES(p_jobname,p_schedule,p_command,true)
                  ON CONFLICT(jobname) DO UPDATE
                    SET schedule=excluded.schedule,command=excluded.command,active=true
                  RETURNING jobid INTO v_id;
                  RETURN v_id;
                END
                $$;

                CREATE TABLE public.properties(
                  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                  parcel_id text UNIQUE,
                  address text,
                  city text,
                  state text DEFAULT 'FL',
                  zip text,
                  county text DEFAULT 'Polk',
                  property_type text,
                  acreage numeric,
                  owner_name text,
                  estimated_market_value numeric,
                  created_at timestamptz DEFAULT now(),
                  updated_at timestamptz DEFAULT now()
                );
                CREATE TABLE public.leads(
                  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                  property_id uuid REFERENCES public.properties(id),
                  contact_name text,
                  phone text,
                  email text,
                  created_at timestamptz DEFAULT now(),
                  updated_at timestamptz DEFAULT now()
                );
                CREATE TABLE public.deals(
                  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                  property_id uuid REFERENCES public.properties(id),
                  lead_id uuid REFERENCES public.leads(id),
                  stage text DEFAULT 'underwriting',
                  estimated_value numeric,
                  repair_cost numeric DEFAULT 0,
                  closing_cost numeric DEFAULT 0,
                  holding_cost numeric DEFAULT 0,
                  risk_reserve numeric DEFAULT 0,
                  target_profit numeric DEFAULT 0,
                  mao numeric,
                  target_offer numeric,
                  expected_exit_price numeric,
                  expected_gross_profit numeric,
                  expected_net_profit numeric,
                  roi numeric,
                  risk_notes text,
                  created_at timestamptz DEFAULT now(),
                  updated_at timestamptz DEFAULT now()
                );
                CREATE TABLE public.due_diligence_reviews(
                  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                  property_id uuid NOT NULL REFERENCES public.properties(id),
                  status text NOT NULL DEFAULT 'queued',
                  title_status text NOT NULL DEFAULT 'pending',
                  access_status text NOT NULL DEFAULT 'pending',
                  comps_status text NOT NULL DEFAULT 'pending',
                  underwriting_status text NOT NULL DEFAULT 'pending',
                  fatal_flags jsonb NOT NULL DEFAULT '[]'::jsonb,
                  completed_at timestamptz,
                  created_at timestamptz NOT NULL DEFAULT now(),
                  updated_at timestamptz NOT NULL DEFAULT now()
                );
                CREATE TABLE public.polk_legal_v2(
                  parcel_id text NOT NULL,
                  num text NOT NULL,
                  dscr text,
                  PRIMARY KEY(parcel_id,num)
                );
                CREATE TABLE public.buyers(
                  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                  name text,
                  company text,
                  active boolean DEFAULT true,
                  qualification_status text DEFAULT 'candidate'
                );
                CREATE TABLE public.buyer_matches(
                  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                  buyer_id uuid NOT NULL REFERENCES public.buyers(id),
                  property_id uuid NOT NULL REFERENCES public.properties(id),
                  match_score numeric NOT NULL DEFAULT 0,
                  rationale text,
                  status text NOT NULL DEFAULT 'candidate',
                  created_at timestamptz NOT NULL DEFAULT now(),
                  updated_at timestamptz NOT NULL DEFAULT now()
                );
                CREATE TABLE public.outreach_events(
                  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                  lead_id uuid REFERENCES public.leads(id),
                  channel text,
                  direction text,
                  status text,
                  message text,
                  occurred_at timestamptz DEFAULT now()
                );
                """
            )
            for migration in MIGRATIONS:
                c.execute(migration.read_text(encoding="utf-8"))

    def q(self, sql, args=None):
        with self.db, self.db.cursor() as c:
            c.execute(sql, args)
            return c.fetchone() if c.description else None

    def make_deal(self, property_type="VACANT LAND", suffix="1"):
        property_id = self.q(
            """
            INSERT INTO public.properties(
              parcel_id,address,city,state,zip,county,property_type,acreage,owner_name,estimated_market_value
            ) VALUES(%s,%s,'Lake Wales','FL','33853','Polk',%s,%s,%s,200000)
            RETURNING id
            """,
            (f"PARCEL-{suffix}", f"{suffix} Test Rd", property_type, 1.25, f"Owner {suffix}"),
        )[0]
        lead_id = self.q(
            """
            INSERT INTO public.leads(property_id,contact_name,phone,email)
            VALUES(%s,%s,%s,%s) RETURNING id
            """,
            (property_id, f"Owner {suffix}", "+18635550000", f"owner{suffix}@example.test"),
        )[0]
        deal_id = self.q(
            """
            INSERT INTO public.deals(property_id,lead_id,stage,risk_notes)
            VALUES(%s,%s,'qualified','tx-test') RETURNING id
            """,
            (property_id, lead_id),
        )[0]
        self.q("INSERT INTO god_mode_ops.deal_workflow(deal_id,state) VALUES(%s,'QUALIFIED')", (deal_id,))
        self.q(
            """
            SELECT god_mode_ops.set_deal_economics(
              %s,200000,30000,5000,5000,10000,15000,1000
            )
            """,
            (deal_id,),
        )
        return property_id, lead_id, deal_id

    def set_offer_gates(self, deal_id, source_status="PASS"):
        # Evidence-backed gates are recalculated by refresh_deal_gates. Give the
        # fixture real DD/legal rows instead of force-setting those statuses.
        self.q(
            """
            INSERT INTO public.due_diligence_reviews(
              property_id,status,title_status,access_status,comps_status,
              underwriting_status,fatal_flags,completed_at
            )
            SELECT d.property_id,'completed','cleared','mapped_road_proximity_verified',
                   'qualified','passed','[]'::jsonb,now()
            FROM public.deals d
            WHERE d.id=%s
              AND NOT EXISTS (
                SELECT 1 FROM public.due_diligence_reviews dd
                WHERE dd.property_id=d.property_id AND dd.status='completed'
              )
            """,
            (deal_id,),
        )
        self.q(
            """
            INSERT INTO public.polk_legal_v2(parcel_id,num,dscr)
            SELECT p.parcel_id,'1','TEST LEGAL DESCRIPTION'
            FROM public.deals d
            JOIN public.properties p ON p.id=d.property_id
            WHERE d.id=%s
            ON CONFLICT(parcel_id,num) DO NOTHING
            """,
            (deal_id,),
        )
        for gate in ("CONTACT_IDENTITY", "COMPLIANCE"):
            self.q(
                "SELECT god_mode_ops.set_gate(%s,%s,'PASS','{}'::jsonb,'test')",
                (deal_id, gate),
            )
        if source_status == "WAIVED":
            self.q(
                """
                SELECT god_mode_ops.set_gate(
                  %s,'SOURCE_RISK','WAIVED','{}'::jsonb,'test','lili','reviewed source-risk evidence'
                )
                """,
                (deal_id,),
            )
        else:
            self.q(
                "SELECT god_mode_ops.set_gate(%s,'SOURCE_RISK','PASS','{}'::jsonb,'test')",
                (deal_id,),
            )
        self.q("SELECT god_mode_ops.refresh_deal_gates(%s)", (deal_id,))

    def approve_offer(self, deal_id):
        snapshot_id = self.q(
            """
            SELECT id FROM god_mode_ops.deal_evidence_snapshots
            WHERE deal_id=%s ORDER BY snapshot_version DESC LIMIT 1
            """,
            (deal_id,),
        )[0]
        self.q(
            """
            INSERT INTO god_mode_ops.deal_approvals(
              deal_id,deal_snapshot_id,approval_type,actor_type,actor_id
            ) VALUES(%s,%s,'OFFER','human_operator','lili')
            """,
            (deal_id, snapshot_id),
        )
        return snapshot_id

    def advance_to_human_approved(self, deal_id):
        self.set_offer_gates(deal_id)
        self.assertEqual(
            self.q(
                "SELECT god_mode_ops.advance_deal_state(%s,'OFFER_READY','test',NULL,'gates pass')",
                (deal_id,),
            )[0],
            "OFFER_READY",
        )
        snapshot_id = self.approve_offer(deal_id)
        self.assertEqual(
            self.q(
                "SELECT god_mode_ops.advance_deal_state(%s,'HUMAN_APPROVED','human','lili','approved')",
                (deal_id,),
            )[0],
            "HUMAN_APPROVED",
        )
        return snapshot_id

    def add_contract_draft(self, deal_id, snapshot_id, key_suffix="1"):
        template_id = self.q(
            """
            INSERT INTO god_mode_ops.contract_templates(
              template_key,version,jurisdiction,asset_type,contract_type,content,
              required_variables,status,approved_by,approved_at,effective_from
            ) VALUES(
              %s,1,'Florida','ANY','ACQUISITION','TEST TEMPLATE',
              ARRAY['purchase_price'],'APPROVED','lili',now(),current_date
            ) RETURNING id
            """,
            (f"purchase-{key_suffix}",),
        )[0]
        contract_id = self.q(
            """
            INSERT INTO god_mode_ops.contracts(
              deal_id,contract_type,template_id,deal_snapshot_id,status,binding_status,
              rendered_payload,document_hash,idempotency_key
            ) VALUES(
              %s,'ACQUISITION',%s,%s,'DRAFTED','NON_BINDING',
              '{"purchase_price":135000}'::jsonb,%s,%s
            ) RETURNING id
            """,
            (deal_id, template_id, snapshot_id, f"hash-{key_suffix}", f"contract:v1:{deal_id}:{key_suffix}"),
        )[0]
        return contract_id

    def test_math_is_deterministic(self):
        row = self.q(
            "SELECT * FROM god_mode_ops.calculate_deal_economics(200000,30000,5000,5000,10000,15000,1000)"
        )
        self.assertEqual(row, (135000, 135000, 15000, 1000, 15000))

    def test_land_and_residential_start_fail_closed(self):
        for kind, suffix in (("VACANT LAND", "land"), ("SINGLE FAMILY", "house")):
            with self.subTest(kind=kind):
                _, _, deal_id = self.make_deal(kind, suffix)
                self.q("SELECT god_mode_ops.refresh_deal_gates(%s)", (deal_id,))
                self.assertEqual(self.q("SELECT god_mode_ops.required_gates_satisfied(%s)", (deal_id,))[0], False)
                with self.assertRaises(psycopg2.Error):
                    self.q("SELECT god_mode_ops.advance_deal_state(%s,'OFFER_READY')", (deal_id,))
                self.assertEqual(
                    self.q("SELECT state FROM god_mode_ops.deal_workflow WHERE deal_id=%s", (deal_id,))[0],
                    "QUALIFIED",
                )

    def test_only_source_risk_can_be_waived(self):
        _, _, deal_id = self.make_deal("VACANT LAND", "waiver")
        with self.assertRaises(psycopg2.Error):
            self.q(
                """
                SELECT god_mode_ops.set_gate(
                  %s,'COMPLIANCE','WAIVED','{}'::jsonb,'test','lili','manual'
                )
                """,
                (deal_id,),
            )
        self.q("ROLLBACK")
        self.set_offer_gates(deal_id, source_status="WAIVED")
        self.assertEqual(self.q("SELECT god_mode_ops.required_gates_satisfied(%s)", (deal_id,))[0], True)

    def test_snapshot_is_idempotent_and_versions_on_material_change(self):
        _, _, deal_id = self.make_deal("VACANT LAND", "snapshot")
        self.set_offer_gates(deal_id)
        first = self.q("SELECT god_mode_ops.create_deal_snapshot(%s)", (deal_id,))[0]
        again = self.q("SELECT god_mode_ops.create_deal_snapshot(%s)", (deal_id,))[0]
        self.assertEqual(first, again)
        self.q(
            "SELECT god_mode_ops.set_deal_economics(%s,210000,30000,5000,5000,10000,15000,1000)",
            (deal_id,),
        )
        second = self.q("SELECT god_mode_ops.create_deal_snapshot(%s)", (deal_id,))[0]
        self.assertNotEqual(first, second)
        self.assertEqual(
            self.q("SELECT count(*) FROM god_mode_ops.deal_evidence_snapshots WHERE deal_id=%s", (deal_id,))[0],
            2,
        )

    def test_human_offer_approval_is_required_and_revocation_is_effective(self):
        _, _, deal_id = self.make_deal("SINGLE FAMILY", "approval")
        self.set_offer_gates(deal_id)
        self.q("SELECT god_mode_ops.advance_deal_state(%s,'OFFER_READY')", (deal_id,))
        with self.assertRaises(psycopg2.Error):
            self.q("SELECT god_mode_ops.advance_deal_state(%s,'HUMAN_APPROVED')", (deal_id,))
        self.q("ROLLBACK")
        snapshot_id = self.q(
            "SELECT id FROM god_mode_ops.deal_evidence_snapshots WHERE deal_id=%s ORDER BY snapshot_version DESC LIMIT 1",
            (deal_id,),
        )[0]
        approval_id = self.q(
            """
            INSERT INTO god_mode_ops.deal_approvals(
              deal_id,deal_snapshot_id,approval_type,actor_type,actor_id
            ) VALUES(%s,%s,'OFFER','human_operator','lili') RETURNING id
            """,
            (deal_id, snapshot_id),
        )[0]
        self.q("UPDATE god_mode_ops.deal_approvals SET revoked_at=now() WHERE id=%s", (approval_id,))
        with self.assertRaises(psycopg2.Error):
            self.q("SELECT god_mode_ops.advance_deal_state(%s,'HUMAN_APPROVED')", (deal_id,))

    def test_contract_esign_and_disposition_are_fail_closed_then_advance(self):
        property_id, _, deal_id = self.make_deal("SINGLE FAMILY", "flow")
        snapshot_id = self.advance_to_human_approved(deal_id)
        contract_id = self.add_contract_draft(deal_id, snapshot_id, "flow")
        self.assertEqual(
            self.q("SELECT god_mode_ops.advance_deal_state(%s,'CONTRACT_DRAFTED')", (deal_id,))[0],
            "CONTRACT_DRAFTED",
        )

        self.q(
            """
            INSERT INTO god_mode_ops.esign_envelopes(
              contract_id,provider,idempotency_key,status
            ) VALUES(%s,'UNCONFIGURED',%s,'PREPARED')
            """,
            (contract_id, f"envelope:unconfigured:{contract_id}"),
        )
        with self.assertRaises(psycopg2.Error):
            self.q("SELECT god_mode_ops.advance_deal_state(%s,'SIGNATURE_READY')", (deal_id,))
        self.q("ROLLBACK")

        self.q(
            """
            INSERT INTO god_mode_ops.deal_approvals(
              deal_id,deal_snapshot_id,approval_type,actor_type,actor_id
            ) VALUES(%s,%s,'ACQUISITION_SIGNATURE','human_operator','lili')
            """,
            (deal_id, snapshot_id),
        )
        self.q(
            """
            INSERT INTO god_mode_ops.esign_envelopes(
              contract_id,provider,idempotency_key,status
            ) VALUES(%s,'test-provider',%s,'PREPARED')
            """,
            (contract_id, f"envelope:test:{contract_id}"),
        )
        self.assertEqual(
            self.q("SELECT god_mode_ops.advance_deal_state(%s,'SIGNATURE_READY')", (deal_id,))[0],
            "SIGNATURE_READY",
        )
        with self.assertRaises(psycopg2.Error):
            self.q("SELECT god_mode_ops.advance_deal_state(%s,'EXECUTED')", (deal_id,))
        self.q("ROLLBACK")

        self.q(
            """
            UPDATE god_mode_ops.esign_envelopes
            SET status='COMPLETED',completed_at=now(),executed_document_ref='test://executed'
            WHERE contract_id=%s AND provider='test-provider'
            """,
            (contract_id,),
        )
        self.assertEqual(
            self.q("SELECT god_mode_ops.advance_deal_state(%s,'EXECUTED')", (deal_id,))[0],
            "EXECUTED",
        )
        self.assertEqual(
            self.q("SELECT binding_status FROM god_mode_ops.contracts WHERE id=%s", (contract_id,))[0],
            "BINDING",
        )

        buyer_id = self.q(
            """
            INSERT INTO public.buyers(name,company,active,qualification_status)
            VALUES('Buyer','Investor LLC',true,'verified_candidate') RETURNING id
            """
        )[0]
        self.q(
            """
            INSERT INTO public.buyer_matches(buyer_id,property_id,match_score,status)
            VALUES(%s,%s,95,'candidate')
            """,
            (buyer_id, property_id),
        )
        result = self.q("SELECT god_mode_ops.run_transaction_automation(100)")[0]
        self.assertEqual(result["advanced_disposition_ready"], 1)
        self.assertEqual(
            self.q("SELECT state FROM god_mode_ops.deal_workflow WHERE deal_id=%s", (deal_id,))[0],
            "DISPOSITION_READY",
        )
        package_id = self.q("SELECT god_mode_ops.prepare_disposition_package(%s)", (deal_id,))[0]
        again = self.q("SELECT god_mode_ops.prepare_disposition_package(%s)", (deal_id,))[0]
        self.assertEqual(package_id, again)

    def test_idempotency_constraints_reject_duplicate_effect_intents(self):
        _, _, deal_id = self.make_deal("VACANT LAND", "idempotency")
        snapshot_id = self.advance_to_human_approved(deal_id)
        contract_id = self.add_contract_draft(deal_id, snapshot_id, "idempotency")

        with self.assertRaises(psycopg2.IntegrityError):
            self.q(
                """
                INSERT INTO god_mode_ops.contracts(
                  deal_id,contract_type,template_id,deal_snapshot_id,status,binding_status,
                  rendered_payload,document_hash,idempotency_key
                )
                SELECT deal_id,contract_type,template_id,deal_snapshot_id,status,binding_status,
                       rendered_payload,'different-hash',idempotency_key
                FROM god_mode_ops.contracts WHERE id=%s
                """,
                (contract_id,),
            )
        self.q("ROLLBACK")

        self.q(
            """
            INSERT INTO god_mode_ops.deal_approvals(
              deal_id,deal_snapshot_id,approval_type,actor_type,actor_id
            ) VALUES(%s,%s,'ACQUISITION_SIGNATURE','human_operator','lili')
            """,
            (deal_id, snapshot_id),
        )
        self.q(
            """
            INSERT INTO god_mode_ops.esign_envelopes(
              contract_id,provider,idempotency_key,status
            ) VALUES(%s,'test-provider','same-envelope-intent','PREPARED')
            """,
            (contract_id,),
        )
        with self.assertRaises(psycopg2.IntegrityError):
            self.q(
                """
                INSERT INTO god_mode_ops.esign_envelopes(
                  contract_id,provider,idempotency_key,status
                ) VALUES(%s,'test-provider','same-envelope-intent','PREPARED')
                """,
                (contract_id,),
            )

    def test_renderer_requires_approved_complete_template_and_esign_requires_signature_approval(self):
        _, _, deal_id = self.make_deal("VACANT LAND", "render")
        snapshot_id = self.advance_to_human_approved(deal_id)
        template_id = self.q(
            """
            INSERT INTO god_mode_ops.contract_templates(
              template_key,version,jurisdiction,asset_type,contract_type,content,
              required_variables,status,approved_by,approved_at,effective_from
            ) VALUES(
              'render-test',1,'Florida','LAND','ACQUISITION',
              'Seller {{seller_name}} | Parcel {{parcel_id}} | Legal {{legal_description}} | Price {{purchase_price}} | EMD {{earnest_money}} | Close {{closing_date}}',
              ARRAY['seller_name','parcel_id','legal_description','purchase_price','earnest_money','closing_date'],
              'APPROVED','lili',now(),current_date
            ) RETURNING id
            """
        )[0]

        with self.assertRaises(psycopg2.Error):
            self.q(
                "SELECT god_mode_ops.render_contract_draft(%s,%s,'{}'::jsonb,%s)",
                (deal_id, template_id, f"render:{deal_id}"),
            )

        contract_id = self.q(
            """
            SELECT god_mode_ops.render_contract_draft(
              %s,%s,'{"closing_date":"2026-10-30"}'::jsonb,%s
            )
            """,
            (deal_id, template_id, f"render:{deal_id}"),
        )[0]
        self.assertEqual(
            self.q("SELECT state FROM god_mode_ops.deal_workflow WHERE deal_id=%s", (deal_id,))[0],
            "CONTRACT_DRAFTED",
        )
        payload = self.q(
            "SELECT rendered_payload FROM god_mode_ops.contracts WHERE id=%s",
            (contract_id,),
        )[0]
        self.assertIn("2026-10-30", payload["document_text"])
        self.assertNotIn("{{", payload["document_text"])
        self.assertTrue(payload["requires_human_signature"])
        self.assertEqual(
            self.q(
                """
                SELECT god_mode_ops.render_contract_draft(
                  %s,%s,'{"closing_date":"2026-10-30"}'::jsonb,%s
                )
                """,
                (deal_id, template_id, f"render:{deal_id}"),
            )[0],
            contract_id,
        )

        with self.assertRaises(psycopg2.Error):
            self.q(
                "SELECT god_mode_ops.prepare_esign_intent(%s,'docusign',%s,'{}'::jsonb)",
                (contract_id, f"esign:{contract_id}"),
            )

        self.q(
            """
            INSERT INTO god_mode_ops.deal_approvals(
              deal_id,deal_snapshot_id,approval_type,actor_type,actor_id
            ) VALUES(%s,%s,'ACQUISITION_SIGNATURE','human_operator','lili')
            """,
            (deal_id, snapshot_id),
        )
        envelope_id = self.q(
            "SELECT god_mode_ops.prepare_esign_intent(%s,'docusign',%s,'{}'::jsonb)",
            (contract_id, f"esign:{contract_id}"),
        )[0]
        self.assertEqual(
            self.q(
                "SELECT god_mode_ops.prepare_esign_intent(%s,'docusign',%s,'{}'::jsonb)",
                (contract_id, f"esign:{contract_id}"),
            )[0],
            envelope_id,
        )

    def test_transaction_worker_never_creates_outreach_or_sent_buyer_messages(self):
        _, _, deal_id = self.make_deal("SINGLE FAMILY", "no-outreach")
        self.q("SELECT god_mode_ops.run_transaction_automation(100)")
        self.assertEqual(self.q("SELECT count(*) FROM public.outreach_events")[0], 0)
        self.assertEqual(
            self.q("SELECT count(*) FROM god_mode_ops.buyer_message_outbox WHERE status='SENT'")[0],
            0,
        )
        self.assertEqual(
            self.q("SELECT state FROM god_mode_ops.deal_workflow WHERE deal_id=%s", (deal_id,))[0],
            "QUALIFIED",
        )

    def test_transaction_cron_is_active_and_bounded(self):
        row = self.q(
            """
            SELECT schedule,active,command
            FROM cron.job WHERE jobname='god_mode_transaction_worker'
            """
        )
        self.assertEqual(row[0], "*/15 * * * *")
        self.assertTrue(row[1])
        self.assertIn("run_transaction_automation(100)", row[2])


if __name__ == "__main__":
    unittest.main()
